### ISSUE TITLE
Working with a database (Chapter 4, pg. 88-89 in book) - Preparing connection info and setting DATABASE_URL

### ISSUE THREAD

**Issue by RustEngineer** [PacktPublishing/Rust-Web-Development-with-Rocket#14]
I am having issues connecting to Hostinger MySQL database.

The book says DATABASE_URL format for other RDBMS might look like: mysql://username:password@localhost:port/db_name

My Hostinger MySQL Database is: u569658_rust_chapter_4
My Hostinger MySQL User is: u569658_rust_engineer

Should I create a .env file and have the following on VSCode: mysql://u569658_rust_engineer:password@localhost:port/u569658_rust_chapter_4

Of course I would change "password" to my actual password as well.

Any help is appreciated. I am enjoying the book thus far. Purchased it last week.

**Comment by karuna** [comment]
DATABASE_URL is a value in [environment variable](https://en.wikipedia.org/wiki/Environment_variable) that your application load. The value in `.env` file is not loaded by default by your shell / terminal. You can use 3rd party program like https://direnv.net/ to load environment variables from `.envrc` file automatically. 

Or you can add configuration to `Cargo.toml` like what explained in page 108 no 2
